### ISSUE TITLE
Vue is not defined error

### ISSUE THREAD

**Issue by pmreyes** [Muetze42/nova-bbcode-textarea#2]
Hi @Muetze42 this looks like a great plugin! Thanks for setting this up. As soon as I installed it via composer and tried some of your sample code, I'm getting this error in the console:

![image](https://user-images.githubusercontent.com/81602852/170051188-69b3537c-ccba-4069-91a1-3c1da9b09989.png)

and as a result it doesn't show the BBCodes:
![image](https://user-images.githubusercontent.com/81602852/170051866-6839336b-2cd5-492e-8863-8ea52469d04e.png)

I'm using Nova 3.0 by the way. I hope it's also compatible with Nova v3.

**Comment by Muetze42** [comment]
Sorry. This package works only with Nova 4+
